import os
from pathlib import Path
from typing import Dict, Any, Optional, Callable

class HostFSManager:
    """
    Generates PCSX2 HostFS patch files (.pnach) and configures the `dds3data` directory
    for real-time testing of DDS1 modifications without rebuilding DDS3.IMG.
    """

    # CRC hashes for Digital Devil Saga 1 versions in PCSX2
    GAME_CRCS = {
        "SLES_534.58": "9F69CD63",  # Europe PAL
        "SLUS_209.74": "B987C651",  # USA NTSC
    }

    def __init__(self, work_dir: str):
        self.work_dir = Path(work_dir)
        self.hostfs_dir = self.work_dir / "dds3data"

    def setup_hostfs_directory(self, logger: Optional[Callable] = None) -> str:
        """Ensures the dds3data directory exists with appropriate subfolders."""
        subdirs = ["event", "facility", "camp", "battle", "font", "title"]
        self.hostfs_dir.mkdir(parents=True, exist_ok=True)
        
        for sub in subdirs:
            (self.hostfs_dir / sub).mkdir(parents=True, exist_ok=True)

        if logger:
            logger(f"Dossier HostFS prêt : {self.hostfs_dir}", "success")

        return str(self.hostfs_dir)

    def generate_pnach_patch(self, elf_name: str = "SLES_534.58", output_dir: Optional[str] = None) -> str:
        """
        Generates a PCSX2 .pnach file to enable Host Filesystem (HostFS) redirection.
        """
        crc = self.GAME_CRCS.get(elf_name, "9F69CD63")
        target_dir = Path(output_dir) if output_dir else self.work_dir
        target_dir.mkdir(parents=True, exist_ok=True)

        pnach_filename = f"{crc}.pnach"
        pnach_path = target_dir / pnach_filename

        content = f"""// Digital Devil Saga 1 - HostFS Redirection Patch
// Game ELF: {elf_name} (CRC: {crc})
// Generated by DDS1 Tool

gametitle=Shin Megami Tensei: Digital Devil Saga 1 [HostFS Patch]
comment=Enables HostFS loading from local dds3data folder for translation testing

[HostFS Redirection]
// Enable HostFS file replacement in PCSX2
patch=1,EE,00100000,extended,00000001
"""
        with open(pnach_path, "w", encoding="utf-8") as f:
            f.write(content)

        return str(pnach_path)
